# Generated by Django 5.2.5 on 2025-09-05 15:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_task_add_date_alter_task_add_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['add_datetime']},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='add_date',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='add_time',
        ),
        migrations.AddField(
            model_name='comment',
            name='add_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
